version: '3.8'

services:
  postgres:
    image: postgres
    container_name: airum
    environment:
      POSTGRES_DB: airum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
    ports:
      - "3432:5432"
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 5