spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/agile
    username: root
    password: 12345678

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    show-sql: true
