server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:3432/airum?currentSchema=airum
    username: postgres
    password: 123123
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:3432/airum?currentSchema=airum
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    encoding: UTF-8
    create-schemas: true
    schemas: airum

    h2:
      console:
        enabled: true
        settings:
          web-allow-others: true


springdoc:
  webjars:
    prefix:
  swagger-ui:
    path: /agile/v1/swagger-ui.html
    disable-swagger-default-url: true
    enabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    doc-expansion: none
  api-docs:
    enabled: true
    path: /agile/v1/api-docs
