server:
  port: 8080
  servlet:
    context-path: /

spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost/agile
    username: agile
    password: 123123

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

springdoc:
  webjars:
    prefix:
  swagger-ui:
    path: /agile/v1/swagger-ui.html
    disable-swagger-default-url: true
    enabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    doc-expansion: none
  api-docs:
    enabled: true
    path: /agile/v1/api-docs
