version: '3.7'
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=agile
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=agile
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=karadiaur.oleksandr@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1231234
    ports:
      - "5050:80"